### SUDDIVISIONE PER ANNI ###

In [2]:
import pandas as pd
shark_clean = pd.read_csv('shark_clean.csv')
shark_clean

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,sex
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,Greg O'Neil,male,63,Body not recovered,Y,1015hrs,Great White Shark 6m (20ft),not defined
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,Unknown Male,male,?,Injuries to chest shoulder and back,N,1030hrs,Great White Shark,not defined
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,Unknown Austrian Tourist,female,37,Serious injuries to right ankle,N,1730hrs,Unknown,not defined
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,Mel Ismail,male,50's,Foot lost in attack,N,0945hrs,Unknown,not defined
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,Wants to remain anonymous,male,24,Scrapes on inside of legs,N,1640hrs,Tiger Shark suspected,not defined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7116,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,male,No_Age,FATAL,Y,Unspecified,Unspecified,not defined
7117,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unspecified,Diving,Ahmun,male,No_Age,FATAL,Y,Unspecified,Unspecified,not defined
7118,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,male,No_Age,FATAL,Y,Unspecified,Unspecified,not defined
7119,1883-1889,0.0,Unprovoked,PANAMA,PANAMA,"Panama Bay 8ºN, 79ºW",Not_defined,Jules Patterson,male,No_Age,FATAL,Y,Unspecified,Unspecified,not defined
7120,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,male,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,Unspecified,Unspecified,not defined

In [2]:
shark_clean.groupby("Year")['Fatal Y/N'].value_counts()

Year    Fatal Y/N
0.0     N            66
        Y            60
        Unknown       3
5.0     N             1
77.0    Y             1
                     ..
2024.0  Unknown       1
2025.0  N            54
        Y            15
2026.0  N            52
        Y             9
Name: count, Length: 608, dtype: int64

In [ ]:
fataYN = shark_clean.groupby("Sex")["Fatal Y/N"].value_counts()
fataYN
fataYN.unstack()

Fatal Y/N       N  Unknown     Y
Sex
female        625       70   125
male         3997      459  1260
not defined   363      112   110

In [14]:
fatal_percentage = (
    shark_clean
    .groupby("Sex")["Fatal Y/N"]
    .value_counts(normalize=True)
    .mul(100)
    .unstack(fill_value=0)
    .round(2)
)

fatal_percentage

Fatal Y/N        N  Unknown      Y
Sex
female       76.22     8.54  15.24
male         69.93     8.03  22.04
not defined  62.05    19.15  18.80

In [ ]:
fatal_percentage.columns = ["No Fatal %", "Unknown", "Yes Fatal %" ]
fatal_percentage

             No Fatal %  Unknown  Yes Fatal %
Sex
female            76.22     8.54        15.24
male              69.93     8.03        22.04
not defined       62.05    19.15        18.80

In [17]:
shark_clean["Fatal Y/N"].value_counts(normalize=True) * 100

Fatal Y/N
N          70.004213
Y          20.994242
Unknown     9.001545
Name: proportion, dtype: float64

In [18]:
fatal_percentage = (
    shark_clean
    .groupby(["Sex", "Fatal Y/N"])
    .size()
    .unstack(fill_value=0)
    .div(len(shark_clean))
    .mul(100)
    .round(2)
)

fatal_percentage.columns = [
    "No Fatal %",
    "Unknown %",
    "Yes Fatal %"
]

fatal_percentage

             No Fatal %  Unknown %  Yes Fatal %
Sex
female             8.78       0.98         1.76
male              56.13       6.45        17.69
not defined        5.10       1.57         1.54

In [19]:
known = shark_clean[shark_clean["Fatal Y/N"] != "Unknown"]
decade = known["Year"] // 10 * 10

table = pd.crosstab(decade, known["Fatal Y/N"])
table["fatality_rate"] = (table["Y"] / (table["Y"] + table["N"]) * 100).round(1)
table

Fatal Y/N     N    Y  fatality_rate
Year
0.0          67   60           47.2
70.0          0    1          100.0
1000.0        1    0            0.0
1500.0        1    0            0.0
1510.0        1    0            0.0
1540.0        0    1          100.0
1580.0        0    1          100.0
1640.0        0    2          100.0
1690.0        0    1          100.0
1700.0        2    2           50.0
1720.0        0    1          100.0
1730.0        0    1          100.0
1740.0        1    2           66.7
1750.0        1    2           66.7
1760.0        0    1          100.0
1770.0        0    4          100.0
1780.0        1    6           85.7
1790.0        0    3          100.0
1800.0        5    5           50.0
1810.0        2    7           77.8
1820.0        6    9           60.0
1830.0        6   10           62.5
1840.0       15   25           62.5
1850.0        8   27           77.1
1860.0       24   37           60.7
1870.0       46   33           41.8
1880.0       47   54           53.5
1890.0       58   71           55.0
1900.0       53   76           58.9
1910.0       72   59           45.0
1920.0      115   73           38.8
1930.0      164   84           33.9
1940.0      157  103           39.6
1950.0      289  136           32.0
1960.0      422  112           21.0
1970.0      248   68           21.5
1980.0      327   52           13.7
1990.0      442   90           16.9
2000.0      835  101           10.8
2010.0     1071   88            7.6
2020.0      498   87           14.9

In [20]:
known = shark_clean[
    (shark_clean["Fatal Y/N"] != "Unknown") &
    (shark_clean["Year"] >= 1990)
]

table = pd.crosstab(known["Year"], known["Fatal Y/N"])

table["fatality_rate"] = (
    table["Y"] / (table["Y"] + table["N"]) * 100
).round(1)

table

Fatal Y/N    N   Y  fatality_rate
Year
1990.0      33   3            8.3
1991.0      32   6           15.8
1992.0      41   9           18.0
1993.0      39  16           29.1
1994.0      43  11           20.4
1995.0      53  12           18.5
1996.0      45  11           19.6
1997.0      44   8           15.4
1998.0      54   9           14.3
1999.0      58   5            7.9
2000.0      73  18           19.8
2001.0      81   6            6.9
2002.0      74  10           11.9
2003.0      78   8            9.3
2004.0      69  14           16.9
2005.0      84   7            7.7
2006.0      83  10           10.8
2007.0      96   5            5.0
2008.0     100  10            9.1
2009.0      97  13           11.8
2010.0      89   8            8.2
2011.0     104  14           11.9
2012.0      98   9            8.4
2013.0     101  13           11.4
2014.0     110   7            6.0
2015.0     121   9            6.9
2016.0     114   6            5.0
2017.0     120   8            6.2
2018.0     115   6            5.0
2019.0      99   8            7.5
2020.0      85  14           14.1
2021.0      94  13           12.1
2022.0      85  11           11.5
2023.0      85  17           16.7
2024.0      43   8           15.7
2025.0      54  15           21.7
2026.0      52   9           14.8

In [19]:
mask = shark_clean["Activity"].value_counts()[shark_clean["Activity"].value_counts() >= 70]

In [16]:
shark_clean["Activity"].value_counts()[shark_clean["Activity"].value_counts() >= 70]

Activity
Surfing         1503
Swimming        1388
Fishing         1368
Diving           710
Not_defined      583
Wading           201
Bathing          189
Boating          188
Standing         135
Sea Disaster     122
Name: count, dtype: int64

In [23]:
known = shark_clean[shark_clean["Fatal Y/N"] != "Unknown"]

counts = known["Activity"].value_counts()
common = counts[counts >= 70].index
subset = known[known["Activity"].isin(common)]

pd.crosstab(subset["Activity"], subset["Fatal Y/N"], normalize="index") * 100

Fatal Y/N             N          Y
Activity
Bathing       51.461988  48.538012
Boating       38.554217  61.445783
Diving        75.937500  24.062500
Fishing       85.280374  14.719626
Not_defined   74.047619  25.952381
Sea Disaster  21.428571  78.571429
Standing      84.962406  15.037594
Surfing       93.485793   6.514207
Swimming      62.954186  37.045814
Wading        87.830688  12.169312

In [ ]:
shark_clean["Country"].value_counts()

np.float64(26.276752767527675)

In [27]:
shark_clean["Country"].value_counts()[shark_clean["Country"].value_counts() >= 70]

Country
USA                 2596
AUSTRALIA           1481
SOUTH AFRICA         597
NEW ZEALAND          144
BAHAMAS              136
PAPUA NEW GUINEA     136
BRAZIL               122
MEXICO               103
ITALY                 72
Name: count, dtype: int64

In [31]:
known = shark_clean[shark_clean["Fatal Y/N"] != "Unknown"]

counts = known["Country"].value_counts()
common = counts[counts >= 50].index
subset = known[known["Country"].isin(common)]

table = (
    pd.crosstab(
        subset["Country"],
        subset["Fatal Y/N"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

average = table.mean()

# Tabella 1: percentuale Y dal valore più alto al più basso
table_by_y = table.sort_values("Y", ascending=False)
table_by_y.loc["Average"] = average

# Tabella 2: percentuale N dal valore più alto al più basso
table_by_n = table.sort_values("N", ascending=False)
table_by_n.loc["Average"] = average

display(table_by_y)
display(table_by_n)

Fatal Y/N                 N          Y
Country
PHILIPPINES       38.600000  61.400000
MEXICO            47.830000  52.170000
REUNION           51.670000  48.330000
PAPUA NEW GUINEA  56.060000  43.940000
NEW CALEDONIA     61.900000  38.100000
BRAZIL            64.860000  35.140000
FIJI              66.670000  33.330000
ITALY             74.550000  25.450000
AUSTRALIA         77.390000  22.610000
Australia         78.570000  21.430000
SOUTH AFRICA      79.430000  20.570000
NEW ZEALAND       80.920000  19.080000
BAHAMAS           88.280000  11.720000
USA               91.610000   8.390000
Average           68.452857  31.547143

Fatal Y/N                 N          Y
Country
USA               91.610000   8.390000
BAHAMAS           88.280000  11.720000
NEW ZEALAND       80.920000  19.080000
SOUTH AFRICA      79.430000  20.570000
Australia         78.570000  21.430000
AUSTRALIA         77.390000  22.610000
ITALY             74.550000  25.450000
FIJI              66.670000  33.330000
BRAZIL            64.860000  35.140000
NEW CALEDONIA     61.900000  38.100000
PAPUA NEW GUINEA  56.060000  43.940000
REUNION           51.670000  48.330000
MEXICO            47.830000  52.170000
PHILIPPINES       38.600000  61.400000
Average           68.452857  31.547143

In [35]:
shark_clean["Type"].value_counts()

Type
Unprovoked     5268
Unconfirmed    1204
Provoked        649
Name: count, dtype: int64

In [36]:
known = shark_clean[shark_clean["Fatal Y/N"] != "Unknown"]

table = pd.crosstab(known["Type"], known["Fatal Y/N"], normalize="index") * 100
table["n"] = known["Type"].value_counts()
table.round(1)

Fatal Y/N       N     Y     n
Type
Provoked     96.7   3.3   640
Unconfirmed  69.2  30.8   650
Unprovoked   75.5  24.5  5190

In [42]:
activity_type = (
    pd.crosstab(
        shark_clean["Activity"],
        shark_clean["Type"],
        normalize="index"
    )
    .mul(100)
)

activity_provoked = activity_type[["Provoked"]].copy()

activity_provoked["n"] = (
    shark_clean["Activity"].value_counts()
)

activity_provoked = (
    activity_provoked
    .round(1)
    .sort_values("Provoked", ascending=False)
)

activity_provoked
activity_provoked = activity_provoked[
    activity_provoked["n"] >= 10
]
activity_provoked

Type           Provoked     n
Activity
Fishing            27.6  1368
Water Skiing       10.0    10
Rescue              9.1    11
Diving              8.2   710
Canoeing            7.1    28
Standing            6.7   135
Washing             6.7    15
Not_defined         6.5   583
Wading              4.5   201
Rowing              4.0    25
Boating             3.2   188
Surfing             1.4  1503
Swimming            1.0  1388
Kayaking            0.0    44
Playing             0.0    26
Walking             0.0    20
Sea Disaster        0.0   122
Bathing             0.0   189
Body boarding       0.0    63

In [43]:
activity_type = (
    pd.crosstab(
        shark_clean["Activity"],
        shark_clean["Type"],
        normalize="index"
    )
    .mul(100)
)

activity_comparison = activity_type[
    ["Provoked", "Unprovoked"]
].copy()

activity_comparison["n"] = (
    shark_clean["Activity"].value_counts()
)

activity_comparison = (
    activity_comparison
    .round(1)
    .sort_values("Provoked", ascending=False)
)

activity_comparison

Type                                                Provoked  Unprovoked  n
Activity
Attempting to lasso a shark                            100.0         0.0  1
Holding shark's tail                                   100.0         0.0  1
Killing  sharks                                        100.0         0.0  1
Stuffing a shark into an automobile                    100.0         0.0  1
Bitten while cutting shark from net                    100.0         0.0  1
...                                                      ...         ... ..
Air disaster. Flash Airlines Boeing 737 crashed...       0.0         0.0  1
Air disaster: crash of Air France Super Constel...       0.0         0.0  1
Air/Sea Disaster                                         0.0         0.0  1
Air/Sea Disaster Pan-American Airlines Stratocr...       0.0         0.0  1
                                                         0.0         0.0  1

[396 rows x 3 columns]